server {
    listen 80;
    listen 443 ssl;
    server_name lms.ducvu.io.vn;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    resolver 1.1.1.1 1.0.0.1 ipv6=off valid=300s;

    location /_mx/lms-api/ {
        proxy_pass https://mindx-proxy.ducvubn1.workers.dev/lms-api/;
        proxy_ssl_server_name on;
        proxy_set_header Host mindx-proxy.ducvubn1.workers.dev;
        proxy_set_header X-Api-Key $http_x_api_key;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 15s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 15s;
        proxy_send_timeout 120s;
        proxy_read_timeout 180s;
    }
}
