server {
    listen 80;
    listen 443 ssl;
    server_name lms.ducvu.io.vn;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    location /_mx/base-api/ {
        proxy_pass https://base-api.mindx.edu.vn/;
        proxy_ssl_server_name on;
        proxy_set_header Host base-api.mindx.edu.vn;
        proxy_set_header Origin https://base.mindx.edu.vn;
        proxy_set_header Referer https://base.mindx.edu.vn/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cookie_domain base-api.mindx.edu.vn lms.ducvu.io.vn;
        proxy_cookie_path / /;
    }

    location /_mx/lms-api/ {
        proxy_pass https://lms-api.mindx.edu.vn/;
        proxy_ssl_server_name on;
        proxy_set_header Host lms-api.mindx.edu.vn;
        proxy_set_header Origin https://lms.mindx.edu.vn;
        proxy_set_header Referer https://lms.mindx.edu.vn/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_mx/identitytoolkit/ {
        proxy_pass https://identitytoolkit.googleapis.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host identitytoolkit.googleapis.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_mx/securetoken/ {
        proxy_pass https://securetoken.googleapis.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host securetoken.googleapis.com;
        proxy_set_header Origin https://lms.mindx.edu.vn;
        proxy_set_header Referer https://lms.mindx.edu.vn/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
